from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import Select
import time
import fspath
import details
import pytest
class TestFibersafeDashboard():
    base_URL = "https://patrol.tmrnd.com.my/portal/login" #production
    @pytest.fixture(scope="session")
    def test_setup(self):
        global driver
        driver = webdriver.Chrome(ChromeDriverManager().install())
        driver.implicitly_wait(10)
        driver.get(self.base_URL)
        driver.maximize_window()
        yield
        print("Test Completed")
        driver.close()
        driver.quit()


    def test_login(self, test_setup):
        driver.find_element_by_id(fspath.Login.login_usrname).send_keys(details.tenantuser)
        driver.find_element_by_id(fspath.Login.login_pass).send_keys(details.tenantpass)
        driver.find_element_by_xpath(fspath.Login.login_button).click()
        time.sleep(2)


    def test_setting(self, test_setup):
        driver.find_element_by_xpath(fspath.Setting.side_bar_setting).click()
        driver.find_element_by_xpath(fspath.Setting.generate_qr).click()
        driver.find_element_by_xpath(fspath.Setting.download_qr).click()
        driver.find_element_by_xpath(fspath.Setting.email_button).click()
        driver.find_element_by_xpath(fspath.Setting.receipents_email).send_keys("test@gmail.com")
        driver.find_element_by_xpath(fspath.Setting.addtional_message).send_keys("testing")
        driver.find_element_by_xpath(fspath.Setting.cancel).click()
        #driver.find_element_by_xpath(fspath.Setting.send_button).click()


    def test_job_assignment_testing_cancel(self, test_setup):
        driver.find_element_by_xpath(fspath.Job.edit_button).click()
        select = Select(driver.find_element_by_xpath(fspath.Job.job_owner_drop))
        select.select_by_visible_text('FM')
        select = Select(driver.find_element_by_xpath(fspath.Job.job_team_member_drop))
        select.select_by_visible_text('NMO')
        driver.find_element_by_xpath(fspath.Job.hour).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.hour).send_keys("3")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.minute).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.minute).send_keys("1")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.job_first_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.job_first_reminder).send_keys("3")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.job_second_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.job_second_reminder).send_keys("2")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.job_third_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.job_third_reminder).send_keys("1")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.contractor_first_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.contractor_first_reminder).send_keys("2")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.contractor_scheduler_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.contractor_scheduler_reminder).send_keys("4")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.radius).send_keys(Keys.BACKSPACE)
        driver.find_element_by_xpath(fspath.Job.radius).send_keys(Keys.BACKSPACE)
        driver.find_element_by_xpath(fspath.Job.radius).send_keys(Keys.BACKSPACE)
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.radius).send_keys("250")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.cancel).click()


    def test_job_assignment_testing_save(self, test_setup):
        driver.find_element_by_xpath(fspath.Job.edit_button).click()
        select = Select(driver.find_element_by_xpath(fspath.Job.job_owner_drop))
        select.select_by_visible_text('FM')
        select = Select(driver.find_element_by_xpath(fspath.Job.job_team_member_drop))
        select.select_by_visible_text('NMO')
        driver.find_element_by_xpath(fspath.Job.hour).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.hour).send_keys("3")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.minute).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.minute).send_keys("1")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.job_first_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.job_first_reminder).send_keys("3")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.job_second_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.job_second_reminder).send_keys("2")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.job_third_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.job_third_reminder).send_keys("1")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.contractor_first_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.contractor_first_reminder).send_keys("2")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.contractor_scheduler_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.contractor_scheduler_reminder).send_keys("4")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.radius).send_keys(Keys.BACKSPACE)
        driver.find_element_by_xpath(fspath.Job.radius).send_keys(Keys.BACKSPACE)
        driver.find_element_by_xpath(fspath.Job.radius).send_keys(Keys.BACKSPACE)
        driver.find_element_by_xpath(fspath.Job.radius).send_keys("250")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.save).click()
        driver.find_element_by_xpath(fspath.Job.cancel_save).click()
        time.sleep(3)
        driver.find_element_by_xpath(fspath.Job.save).click()
        driver.find_element_by_xpath(fspath.Job.yes_save).click()
        time.sleep(3)
        driver.refresh()
        time.sleep(3)


    def test_job_assignment_testing_save_revert(self, test_setup):
        driver.find_element_by_xpath(fspath.Job.edit_button).click()
        select = Select(driver.find_element_by_xpath(fspath.Job.job_owner_drop))
        select.select_by_visible_text('NMO')
        select = Select(driver.find_element_by_xpath(fspath.Job.job_team_member_drop))
        select.select_by_visible_text('ND')
        driver.find_element_by_xpath(fspath.Job.hour).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.hour).send_keys("1")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.minute).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.minute).send_keys("0")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.job_first_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.job_first_reminder).send_keys("2")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.job_second_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.job_second_reminder).send_keys("1")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.contractor_first_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.contractor_first_reminder).send_keys("1")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.contractor_scheduler_reminder).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.contractor_scheduler_reminder).send_keys("3")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.radius).send_keys(Keys.BACKSPACE)
        driver.find_element_by_xpath(fspath.Job.radius).send_keys(Keys.BACKSPACE)
        driver.find_element_by_xpath(fspath.Job.radius).send_keys(Keys.BACKSPACE)
        time.sleep(1)
        driver.find_element_by_xpath(fspath.Job.radius).send_keys("200")
        time.sleep(2)
        driver.find_element_by_xpath(fspath.Job.save).click()
        driver.find_element_by_xpath(fspath.Job.yes_save).click()
        time.sleep(3)


    # def test_post_assessment_setting_cancel(self, test_setup):
    #     driver.find_element_by_xpath(fspath.Post.post).click()
    #     driver.find_element_by_xpath(fspath.Post.edit_button_post).click()
    #     driver.find_element_by_xpath(fspath.Post.low_min).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.low_min).send_keys("1")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.low_max).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.low_max).send_keys("5")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.medium_min).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.medium_min).send_keys("6")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.medium_max).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.medium_max).send_keys("10")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.high_min).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Post.high_min).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.high_min).send_keys("11")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.high_max).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Post.high_max).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.high_max).send_keys("16")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.cancel_post).click()


    # def test_post_assessment_setting_save(self, test_setup):
    #     driver.find_element_by_xpath(fspath.Post.post).click()
    #     driver.find_element_by_xpath(fspath.Post.edit_button_post).click()
    #     driver.find_element_by_xpath(fspath.Post.low_min).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.low_min).send_keys("1")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.low_max).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.low_max).send_keys("5")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.medium_min).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.medium_min).send_keys("6")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.medium_max).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.medium_max).send_keys("10")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.high_min).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Post.high_min).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.high_min).send_keys("11")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.high_max).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Post.high_max).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.high_max).send_keys("16")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.save_post).click()
    #     driver.find_element_by_xpath(fspath.Post.cancel_save).click()
    #     driver.find_element_by_xpath(fspath.Post.save_post).click()
    #     driver.find_element_by_xpath(fspath.Post.yes_save).click()


    # def test_post_assessment_setting_save_revert(self, test_setup):
    #     driver.find_element_by_xpath(fspath.Post.post).click()
    #     driver.find_element_by_xpath(fspath.Post.edit_button_post).click()
    #     driver.find_element_by_xpath(fspath.Post.low_min).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.low_min).send_keys("0")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.low_max).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.low_max).send_keys("4")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.medium_min).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.medium_min).send_keys("5")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.medium_max).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Post.medium_max).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.medium_max).send_keys("9")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.high_min).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Post.high_min).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.high_min).send_keys("10")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Post.high_max).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Post.high_max).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Post.save_post).click()
    #     driver.find_element_by_xpath(fspath.Post.yes_save).click()


    # def test_alert_setting_cancel(self, test_setup):
    #     driver.find_element_by_xpath(fspath.Alert.alert_setting).click()
    #     driver.find_element_by_xpath(fspath.Alert.edit_button_alert).click()
    #     driver.find_element_by_xpath(fspath.Alert.distance_threshold).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Alert.distance_threshold).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Alert.distance_threshold).send_keys("51")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Alert.alert_distance).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Alert.alert_distance).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Alert.alert_distance).send_keys("41")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Alert.duplicate_alert).click()
    #     driver.find_element_by_xpath(fspath.Alert.number_of_days).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Alert.number_of_days).send_keys("3")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Alert.cancel_alert).click()
    #     driver.refresh()


    # def test_alert_setting_save(self, test_setup):
    #     driver.find_element_by_xpath(fspath.Alert.alert_setting).click()
    #     driver.find_element_by_xpath(fspath.Alert.edit_button_alert).click()
    #     driver.find_element_by_xpath(fspath.Alert.distance_threshold).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Alert.distance_threshold).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Alert.distance_threshold).send_keys("51")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Alert.alert_distance).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Alert.alert_distance).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Alert.alert_distance).send_keys("41")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Alert.duplicate_alert).click()
    #     driver.find_element_by_xpath(fspath.Alert.number_of_days).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Alert.number_of_days).send_keys("3")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Alert.save_alert).click()
    #     driver.find_element_by_xpath(fspath.Alert.cancel_save).click()
    #     driver.find_element_by_xpath(fspath.Alert.save_alert).click()
    #     driver.find_element_by_xpath(fspath.Alert.yes_save).click()
    #     driver.refresh()


    # def test_alert_setting_save_revert(self, test_setup):
    #     driver.find_element_by_xpath(fspath.Alert.alert_setting).click()
    #     driver.find_element_by_xpath(fspath.Alert.edit_button_alert).click()
    #     driver.find_element_by_xpath(fspath.Alert.distance_threshold).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Alert.distance_threshold).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Alert.distance_threshold).send_keys("50")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Alert.alert_distance).send_keys(Keys.BACKSPACE)
    #     driver.find_element_by_xpath(fspath.Alert.alert_distance).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Alert.alert_distance).send_keys("40")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Alert.duplicate_alert).click()
    #     driver.find_element_by_xpath(fspath.Alert.number_of_days).send_keys(Keys.BACKSPACE)
    #     time.sleep(1)
    #     driver.find_element_by_xpath(fspath.Alert.number_of_days).send_keys("0")
    #     time.sleep(2)
    #     driver.find_element_by_xpath(fspath.Alert.save_alert).click()
    #     driver.find_element_by_xpath(fspath.Alert.yes_save).click()
